Grossum\ContactBundle\Entity\BaseEmail:
    type: mappedSuperclass
    table: email
    fields:
        email:
            type: string
            length: 255
        enabled:
            type: boolean
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
    lifecycleCallbacks:
            prePersist: [setCreatedAtValue, setUpdatedAtValue]
            preUpdate: [setUpdatedAtValue]

