Grossum\ContactBundle\Entity\BaseContact:
    type: mappedSuperclass
    table: contact
    fields:
        name:
            type: string
            length: 255
            nullable: true
        googleMapCoordinates:
            type: text
            nullable: true
        enabled:
            type: boolean
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
    lifecycleCallbacks:
        prePersist: [setCreatedAtValue, setUpdatedAtValue]
        preUpdate: [setUpdatedAtValue]
