services:
    sonata.admin.contact:
        class: %grossum_contact.contact.admin.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: group.main, label: "Контакты" }
        arguments:
            - ~
            - %grossum_contact.contact.entity.class%
            - ~
        calls:
            - [ setContactManager, [@grossum_contact.contact.manager]]

    sonata.admin.email:
        class: %grossum_contact.email.admin.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: group.hidden, label: "E-Mail'ы" }
        arguments:
            - ~
            - %grossum_contact.email.entity.class%
            - ~
        calls:
            - [ setEmailManager, [@grossum_contact.email.manager]]

    sonata.admin.phone:
        class: %grossum_contact.phone.admin.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: group.hidden, label: "Телефоны" }
        arguments:
            - ~
            - %grossum_contact.phone.entity.class%
            - ~
        calls:
            - [ setPhoneManager, [@grossum_contact.phone.manager]]