services:
    grossum_contact.admin.contact:
        class: %grossum_contact.contact.admin.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: group.main, label: "grossum_contact.admin.contact.plural_label" }
        arguments:
            - ~
            - %grossum_contact.contact.entity.class%
            - ~

    grossum_contact.admin.email:
        class: %grossum_contact.email.admin.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: group.hidden, label: "grossum_contact.admin.email.plural_label" }
        arguments:
            - ~
            - %grossum_contact.email.entity.class%
            - ~

    grossum_contact.admin.phone:
        class: %grossum_contact.phone.admin.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: group.hidden, label: "grossum_contact.admin.phone.plural_label" }
        arguments:
            - ~
            - %grossum_contact.phone.entity.class%
            - ~
