services:
    sonata.admin.contact:
        class: Grossum\ContactBundle\Admin\ContactAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: group.main, label: "Контакты" }
        arguments:
            - ~
            - Grossum\ContactBundle\Entity\Contact
            - ~
        calls:
            - [ setContactManager, [@grossum_contact.contact.manager]]

    sonata.admin.contact_to_email:
        class: Grossum\ContactBundle\Admin\ContactToEmailAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: group.hidden, label: "E-Mail'ы" }
        arguments:
            - ~
            - Grossum\ContactBundle\Entity\ContactToEmail
            - ~
        calls:
            - [ setContactToEmailManager, [@grossum_contact.contact_to_email.manager]]

    sonata.admin.contact_to_phone:
        class: Grossum\ContactBundle\Admin\ContactToPhoneAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: group.hidden, label: "Телефоны" }
        arguments:
            - ~
            - Grossum\ContactBundle\Entity\ContactToPhone
            - ~
        calls:
            - [ setContactToPhoneManager, [@grossum_contact.contact_to_phone.manager]]