services:
    sonata.admin.contact:
        class: %grossum_contact.contact.admin.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: group.main, label: "Контакты" }
        arguments:
            - ~
            - %grossum_contact.contact.entity.class%
            - ~
        calls:
            - [ setContactManager, [@grossum_contact.contact.manager]]

    sonata.admin.contact_to_email:
        class: %grossum_contact.contact_to_email.admin.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: group.hidden, label: "E-Mail'ы" }
        arguments:
            - ~
            - %grossum_contact.contact_to_email.entity.class%
            - ~
        calls:
            - [ setContactToEmailManager, [@grossum_contact.contact_to_email.manager]]

    sonata.admin.contact_to_phone:
        class: %grossum_contact.contact_to_phone.admin.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: group.hidden, label: "Телефоны" }
        arguments:
            - ~
            - %grossum_contact.contact_to_phone.entity.class%
            - ~
        calls:
            - [ setContactToPhoneManager, [@grossum_contact.contact_to_phone.manager]]